/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React from "react";
import {
  Html,
  MeshTransmissionMaterial,
  useGLTF,
  useTexture,
} from "@react-three/drei";
import { configOptions } from "./constants";
import { useControls } from "leva";

function Model(props) {
  const { nodes, materials } = useGLTF("/brink-demo.glb");
  const texture = useTexture("/bake-test.jpg");
  texture.flipY = false;

  return (
    <group {...props} dispose={null}>
      {configOptions.map((option) => {
        return (
          <group key={option.id}>
            {option.tagPosition && (
              <Html occlude position={option.tagPosition}>
                <div className="tag" />
              </Html>
            )}
            <mesh castShadow receiveShadow geometry={nodes[option.id].geometry}>
              {option.glassPanel ? (
                <meshPhysicalMaterial
                  transmission={0}
                  color="#d5d5d5"
                  roughness={0.1}
                  metalness={0.1}
                />
              ) : (
                <meshBasicMaterial
                  color={option.color}
                  map={texture}
                  map-flipY={false}
                />
              )}
            </mesh>
          </group>
        );
      })}
    </group>
  );
}

useGLTF.preload("/brink-demo.glb");

export default Model;
